"""Initial migration.

Revision ID: bc4fcb8d39f7
Revises: 
Create Date: 2024-01-05 18:27:46.575395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4fcb8d39f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('Kod_department', sa.Integer(), nullable=False),
    sa.Column('Department_name', sa.String(length=100), nullable=False),
    sa.Column('Department_floor', sa.Integer(), nullable=True),
    sa.Column('Department_phone', sa.String(length=25), nullable=True),
    sa.Column('Department_fio', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Kod_department')
    )
    op.create_table('organizations',
    sa.Column('Kod_organization', sa.Integer(), nullable=False),
    sa.Column('Organization_name', sa.String(length=100), nullable=False),
    sa.Column('Organization_type', sa.String(length=100), nullable=False),
    sa.Column('Organization_country', sa.String(length=20), nullable=False),
    sa.Column('Organization_city', sa.String(length=20), nullable=False),
    sa.Column('Organization_adress', sa.String(length=100), nullable=False),
    sa.Column('Organization_fio', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Kod_organization')
    )
    op.create_table('contracts',
    sa.Column('Kod_contract', sa.Integer(), nullable=False),
    sa.Column('Kod_organization', sa.Integer(), nullable=True),
    sa.Column('Contract_number', sa.String(length=50), nullable=False),
    sa.Column('Contract_date', sa.String(length=50), nullable=False),
    sa.Column('Contract_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['Kod_organization'], ['organizations.Kod_organization'], ),
    sa.PrimaryKeyConstraint('Kod_contract')
    )
    op.create_table('employees',
    sa.Column('Kod_employee', sa.Integer(), nullable=False),
    sa.Column('Kod_department', sa.Integer(), nullable=True),
    sa.Column('Employee_fio', sa.String(length=150), nullable=False),
    sa.Column('Employee_post', sa.String(length=50), nullable=False),
    sa.Column('Employee_number', sa.Integer(), nullable=False),
    sa.Column('Employee_gender', sa.String(length=25), nullable=False),
    sa.Column('Employee_address', sa.String(length=100), nullable=True),
    sa.Column('Employee_date', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['Kod_department'], ['departments.Kod_department'], ),
    sa.PrimaryKeyConstraint('Kod_employee')
    )
    op.create_table('project_works',
    sa.Column('Kod_work', sa.Integer(), nullable=False),
    sa.Column('Kod_contract', sa.Integer(), nullable=True),
    sa.Column('Kod_department', sa.Integer(), nullable=True),
    sa.Column('Work_start_date', sa.String(length=50), nullable=False),
    sa.Column('Work_end_date', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['Kod_contract'], ['contracts.Kod_contract'], ),
    sa.ForeignKeyConstraint(['Kod_department'], ['departments.Kod_department'], ),
    sa.PrimaryKeyConstraint('Kod_work')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_works')
    op.drop_table('employees')
    op.drop_table('contracts')
    op.drop_table('organizations')
    op.drop_table('departments')
    # ### end Alembic commands ###
